### ISSUE TITLE
Add possibility to change renderer

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#10]
Add a way to change the renderer. The default renderer is the handlebars-html renderer but other people could implement their renderers and hook them in.

**Comment by killercup** [comment]
Feel free to steal any and all code from https://github.com/killercup/trpl-ebook which could allow you to render epub/mobi/html/pdf using pandoc :)

**Comment by azerupi** [comment]
Nice! Thanks a lot, I will definitely take a look :)
