### ISSUE TITLE
CSS broken on newest Firefox

### ISSUE THREAD

**Issue by ebkalderon** [azerupi/mdBook#101]
I am using the latest version of mdBook, and it seems that link colors, the arrow key navigation, the sidebar collapse button, the theme selector, and the print button are all broken on Firefox 44 on Linux. The buttons do not respond, and all of the links appear purple (no colorization for current chapter, either).

Please see the [following link](https://ebkalderon.github.io/amethyst/) and confirm. Below is a screenshot of the same site in both Chromium (left) and Firefox (right).

![screenshot from 2016-01-29 11-07-36](https://cloud.githubusercontent.com/assets/322831/12680632/e48ad5e4-c678-11e5-9eb6-e1d1665b412f.png)

**Comment by azerupi** [comment]
When visiting your link with Firefox 43 I can't reproduce. It's strange that this only occurs on the latest version of Firefox.. I will check it out, if you can procure any other information that would be great!

**Comment by ebkalderon** [comment]
@azerupi I tried it on Firefox 44.0 (32-bit) on Windows 7, and I haven't been able to reproduce it either. I tried clearing my entire browsing history and disabled all add-ons, and nonetheless this continues to occur. Sadly, I don't have another Linux machine to test on. I could spin up a VM maybe...

**Comment by ebkalderon** [comment]
@azerupi Indeed, on Firefox 47a1 Nightly (64-bit) on Linux, the breakage is still there. Please see if you can get some other people to test it. I don't have any VMs with a new enough version of Firefox to compare.

**Comment by ebkalderon** [comment]
@azerupi Never mind, it seems like it was a Firefox Sync problem. Looks like my account got corrupted, and was messing with my cache. The site looks fine after I disconnected from it and restarted the browser. This issue can be closed now. Thanks anyway for responding.

**Comment by azerupi** [comment]
Ah good! I am glad you found the cause of the issue :)
