### ISSUE TITLE
Add an initial `.gitignore`

### ISSUE THREAD

**Issue by vrinek** [azerupi/mdBook#110]
I just started using `mdbook` and the first thing I noticed is that there is no clear way to figure out what should be committed and what's auto-generated.

I assume that the [Rust book's gitignore](https://github.com/rust-lang/book/blob/master/.gitignore) is a good enough default.

**Comment by vrinek** [comment]
Even though I'm new to Rust, I feel like this is an easy task and thus I'll try to create a pull request for it.

**Comment by azerupi** [comment]
I like this idea, however there are a couple of complications that make this more difficult than it first seems:

- You can't assume everyone is going to use version control, so this should be optional and opt-in
- The output directory can be set to any arbitrary path, it doesn't have to be a sub-path of the root directory. And thus it can be outside of the git repository
- A book can be a part of a bigger project, in that case the root directory of the book will not be the root directory of the git repository

**Comment by vrinek** [comment]
I replied on the PR (to keep the discussion centralised) -> https://github.com/azerupi/mdBook/pull/111#issuecomment-188182387

**Comment by azerupi** [comment]
Of course, I was just repeating what I said on the PR that seemed relevant for people who might stumble upon this issue :)

**Comment by vrinek** [comment]
Should we close this one or keep it around until release?

**Comment by azerupi** [comment]
It can be closed :) Thanks!
