### ISSUE TITLE
Don't use `\` as directory separator, not even on Windows

### ISSUE THREAD

**Issue by Evrey** [azerupi/mdBook#119]
Yeah. mdBook generates all links with `.\chapter.html` instead of `./chapter.html` on Windows. This way, I have to edit all links by hand if I plan to load my on-Windows-generated HTML book up on some website.

**Comment by azerupi** [comment]
I don't have a windows machine, so I can't really test this. 

My first guess would be that Rusts Paths are represented that way on windows. I don't know if there is an option to change that. Else I will have make my own path to string method that behaves the same on all platforms.

**Comment by Evrey** [comment]
I guess that Path-to-String solution would be the easiest way to go. Its just a matter of a simple extra `String::replace("\\", "/")` then. You might use [std::path::MAIN_SEPARATOR](https://doc.rust-lang.org/nightly/std/path/constant.MAIN_SEPARATOR.html) if `"\\"` feels too dirty.

In fact, `'/'` is almost always the easiest cross-platform way to go. All Unixoids like Mac OS and Linux use it and Windows accepts it in the Win32API (although `cmd.exe`, the Windows shell, does not know about `'/'`). Thus, the whole standard library works just fine using `'/'` as directory separator.

**Comment by azerupi** [comment]
@Evrey, could you tell me exactly where this happens? 

Is this only for links in the sidebar, navigation, all links?

**Comment by Evrey** [comment]
Right now it looks like only sidebar-/navigation-links are affected, i.e. those links that will be converted from `anything.md` to `anything.html`. All other links seem to be left untouched.

**Comment by azerupi** [comment]
Yes, it's what I thought. So I use path.to_str() and it seems that it uses the `\` separator in windows. I am not sure how I can change that behavior though. 

>> You might use std::path::MAIN_SEPARATOR if "\\" feels too dirty.

Do you know how I could set the `MAIN_SEPARATOR` ?

**Comment by azerupi** [comment]
I have used the `string::replace` hack, but it would need some testing. Could you try it out on windows an let me know if it works? (or broke the world :yum:)

**Comment by Evrey** [comment]
Slashes everywhere, finally! Many thanks.

**Comment by azerupi** [comment]
Good! I will make a release to crates.io in the following days :)
