### ISSUE TITLE
Cargo makes it easier

### ISSUE THREAD

**Issue by lilianmoraru** [azerupi/mdBook#123]
At the ["Install from git"](https://github.com/azerupi/mdBook#install-from-git) chapter, it says "Cargo makes this super easy", but it could be easier:
```
cargo install --git https://github.com/azerupi/mdBook.git
```

But may be it was intended to indirectly show that it is easy to compile the project...

**Comment by azerupi** [comment]
Indeed I forgot about that! Thanks for pointing it out. 
I will add that to the README, unless you want to make a PR?

**Comment by lilianmoraru** [comment]
I wanted to make a PR but I thought may be it was intended, so I opened an issue :)
I'll pass on PR.
