### ISSUE TITLE
Can not close sidebar on mobile

### ISSUE THREAD

**Issue by LucioFranco** [azerupi/mdBook#125]
I am not able to close the sidebar menu to be able to read the book when I am on mobile.

**Comment by azerupi** [comment]
There are definitely some quirks with the "mobile version". Could you give more information about your mobile device? I am able to show and hide the sidebar on my one plus one, although there are other stylistic / usability issues.

**Comment by LucioFranco** [comment]
@azerupi I was on an iPhone 5. What did you do to close it because I could not find a button and it did not close automatedly when I clicked on a link item.

**Comment by azerupi** [comment]
I guess I see it because my screen is a little larger. This is definitely a
bug and the mobile version should be improved. It may be interesting to
explore touch navigation too.

**Comment by LucioFranco** [comment]
@azerupi So when I click that area on the iPhone 5 emulator on chrome dev tools it works but it doesn't work when I actually do it on my phone. Maybe just move the hamburger menu to the part that slides out?

**Comment by thomastanck** [comment]
+1 I have the exact same problem on my iPhone 5. It's a bit annoying since I have to change the orientation to landscape before I am able to click the retract button.

Any progress on this?

**Comment by azerupi** [comment]
I haven't looked into it yet. I am not sure what the best solution would be.

**Comment by JIghtuse** [comment]
I tried to solve it (see commit above).

How about making sidebar a bit lower to make sure hamburger is visible? It makes sidebar look a bit weird when you scroll the page, but it can be fixed I guess.

Screenshot in DevTools emulating iPhone5:
![screenshot](http://i.imgur.com/V6jBvdL.png)

**Comment by budziq** [comment]
How about just closing the sidebar automatically after selection when on mobile? 

Actually having to close sidebar manually on mobile it is driving me nuts.
It should be relatively easy to detect with `if (typeof window.orientation !== 'undefined') { ... }` as only mobile browsers should support this feature

**Comment by azerupi** [comment]
On mobile (small screens) closing the sidebar seems like a good default behaviour. However I don't think it would be appropriate for tablets with larger screens.

**Comment by budziq** [comment]
Yeah that is why I was thinking about the second solution in previous post. Arbitrarily deciding if screen is small via css and acting on it. I'm bored out of my mind on sick leave so I might as well tinker a little ;)
