### ISSUE TITLE
Add a handlebar helper to include the contents of a file

### ISSUE THREAD

**Issue by japaric** [azerupi/mdBook#140]
Rationale: If you already have said file sitting around in your repository (for e.g. testing purposes), it saves you the trouble of copy-pasting the contents of the file _and_ keeping the copy-pasted version in sync with the original.

It would be like the `{{#playpen foo.rs}}` helper but not limited to Rust files and without the playpen functionality. Example below:

You write:

``````
The target specification file looks like this:

``` js
{{#include cortex-m3.json}}
```
``````

And it gets rendered as:

![2016-05-09t21 46 28z](https://cloud.githubusercontent.com/assets/5018213/15134236/d2865448-162f-11e6-834e-f9c3ebfec4e3.jpg)

**Comment by azerupi** [comment]
This is a good idea!
However, a couple of months back I tried to see if users could use the handlebars helpers, I defined, in their markdown and they could not currently. If I want to make this possible I have to add another rendering pass on the rendered markdown.

Also I am a little worried of how this all might work when I finally get around to add pdf / epub / latex export.

If you have any ideas, feel free to share :wink:
