### ISSUE TITLE
Trying to have links with code in them does not create `<a>` tags; breaks following links

### ISSUE THREAD

**Issue by carols10cents** [azerupi/mdBook#154]
I have a full example in this repo: https://github.com/carols10cents/mdbook-code-link-bug
And the rendered version on a gh-pages branch: https://carols10cents.github.io/mdbook-code-link-bug/

What's happening is I'm trying to make code-formatted text with backticks be a link, so:

```
blah blah blah [`structs`] blah blah

[`structs`]: https://doc.rust-lang.org/stable/book/structs.html
```

and this generates the markup:

```
<p>
blah blah blah [
<code class="hljs">structs</code>
] blah blah
</p>
<p>
[
<code class="hljs">structs</code>
]: https://doc.rust-lang.org/stable/book/structs.html
</p>
```

when I expected to get:

```
<p>
blah blah blah <a href="https://doc.rust-lang.org/stable/book/structs.html"><code>structs</code></a> blah blah
</p>
```

Also, if there are any other links in the same paragraph following the link with code, those links aren't rendered as `<a>` tags either. Starting a new paragraph seems to fix things and links work again.

**Comment by azerupi** [comment]
At first I wanted to say that it probably was a bug in pulldown-cmark but I did some tests and it seems to render this example correctly with the master branch. 

I am not using the latest release (v0.0.8) of pulldown-cmark, but still using 0.0.7, so the fix might be in the latest release.

**Comment by azerupi** [comment]
It looks like it has been resolved by upgrading pulldown-cmark. I have pushed the new version to crates.io. Could you double check to make sure it is really fixed? :)

**Comment by carols10cents** [comment]
It is indeed fixed!!! Thank you so much!!! 💯
