### ISSUE TITLE
anchors with spaces

### ISSUE THREAD

**Issue by icanrealizeum** [azerupi/mdBook#156]
Hello. Clicking on anchors generate urls with spaces which seem unusable when trying to link to, for example here:
https://rust-lang.github.io/book/ch04-02-ownership.html#Variable binding scope

Is there a way to make the spaces be %20 or whatever is idiomatic in these cases?
Thanks.

**Comment by azerupi** [comment]
Yes, the code responsible for this is [here](https://github.com/azerupi/mdBook/blob/master/src/theme/book.js#L55-L62). I guess the best action is to convert spaces to underscores and check if the url already contains a hashtag.

**Comment by icanrealizeum** [comment]
The only issue would be, I would think, that if spaces now become underscores, any previous urls with `%20` instead of space, anywhere on the net already, would stop working.
Eg. in OP, this url 
https://rust-lang.github.io/book/ch04-02-ownership.html#Variable binding scope
with `%20` currently works:
https://rust-lang.github.io/book/ch04-02-ownership.html#Variable%20binding%20scope
and I've used this url myself in places.

So after the fix of spaces to underscores, it won't work anymore; only this would then work:
https://rust-lang.github.io/book/ch04-02-ownership.html#Variable_binding_scope

I'm not sure how much this backward-compatibility should matter on deciding whether or not to implement the spaces to underscores. Just putting it out there.

**Comment by azerupi** [comment]
>I'm not sure how much this backward-compatibility should matter on deciding

You're right, I have always announced mdBook as "unstable" to allow for changes like these. But I can understand that this could be a pain.

I don't feel strongly about one (`_`) or the other (`%20`), both solutions are fine for me. If the latter one can minimize breakage, let's do that.

**Comment by icanrealizeum** [comment]
Cool. I guess I could make a PR with `%20` and if you later decide to change them to `_` that's okay too - it makes sense now since (I didn't know that) mdBook is to be treated as "unstable" (haven't read the readme yet, oops)

Thanks for pointing me to the code above. I'll see if I can figure out how to do this with my limited know-how :D

Cheers!
