### ISSUE TITLE
[CI] musl build fails

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#158]
@japaric hey, sorry to annoy you again with this :confused: 

Recently my musl build started failing and I am not sure what is going on. The [travis log](https://travis-ci.org/azerupi/mdBook/jobs/148857608) says:

```
error: linking with `cc` failed: exit code: 1
```

And a little further

```
note: /usr/bin/ld: BFD (GNU Binutils for Ubuntu) 2.22 internal error, aborting at ../../bfd/reloc.c line 443 in bfd_get_reloc_size
/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

error: aborting due to previous error
error: Could not compile `mdbook`.
```

Do you have an idea on how I might solve this?

**Comment by japaric** [comment]
This is probably rust-lang/rust#34978. I'd suggest to just disable (allowed_failures) the musl target on nightly until that it's fixed. The other solution is to upgrade the binutils in the Travis builder, which is not trivial.

**Comment by azerupi** [comment]
Thanks! It seems to be related to that issue indeed

>I'd suggest to just disable (allowed_failures) the musl target on nightly until that's fixed.

It's already affecting beta too, so I guess I will allow failure for all channels for the musl build until it gets fixed.

Thanks for your help :)

**Comment by code-ape** [comment]
Is there a published artifact for the `musl` build of mdBook? I've been building my own to run on alpine Docker containers and just saw this in passing.

**Comment by azerupi** [comment]
There is, but not for the latest release due to this bug.
You can find them under the releases section: https://github.com/azerupi/mdBook/releases

**Comment by code-ape** [comment]
Oh, ok! Thanks. I just thought that there may have been some other reason since the stable build for [musl succeeded](https://travis-ci.org/azerupi/mdBook/jobs/148857570) in the [build you referenced](https://travis-ci.org/azerupi/mdBook/builds/148857565) and after that build Travis CI [doesn't appeal to run the musl builds at all any more](https://travis-ci.org/azerupi/mdBook/builds/148951170).

**Comment by azerupi** [comment]
Since the bug was also present in beta, I anticipated that it would propagate to stable unless it was fixed before the next release. So I just allowed all musl builds to fail. 

> Travis CI doesn't appeal to run the musl builds at all any more.

I noticed that too, but I am not sure why... I don't have a ton of experience with Travis and it's possible that I changed something that I shouldn't have. The behavior I wanted was to run the musl builds but not complain if they failed.

**Comment by japaric** [comment]
> I noticed that too, but I am not sure why... I don't have a ton of experience with Travis and it's possible that I changed something that I shouldn't have. The behavior I wanted was to run the musl builds but not complain if they failed.

@azerupi 

I just looked at https://github.com/azerupi/mdBook/commit/02c5c971e7c206f78299f15225be957fe106e64b and you should have not removed any line from .travis.yml to get the behavior you describe (IOW, only adding the build jobs to allowed_failures was necessary)

**Comment by azerupi** [comment]
Ah, I see. It all makes sense now.

Thanks a lot for taking a look! :)

**Comment by lilianmoraru** [comment]
This should work again(at least on nightly).

**Comment by azerupi** [comment]
This is probably fixed since a long time. I think, if it is not already done, we can re-add the musl builds to fail CI if they error. Once that's done and CI is still green we can close this issue.
