### ISSUE TITLE
Allow serve host to be configured to things other than localhost

### ISSUE THREAD

**Issue by code-ape** [azerupi/mdBook#159]
I love using mdBook but there are times when I want to use it on a VM. However I can't use the serve function to watch the live reload currently. Would you be interested in making this a feature? I'm happy to do the change and PR if so! 😃 

Cheers,
code-ape

**Comment by azerupi** [comment]
For sure, if you send a PR I will gladly accept it! :wink:

**Comment by azerupi** [comment]
Closed with #160
