### ISSUE TITLE
Spacing in sidebar

### ISSUE THREAD

**Issue by dtolnay** [azerupi/mdBook#166]
![selection_007](https://cloud.githubusercontent.com/assets/1940490/18036971/00f3f452-6d2e-11e6-8cc4-eb2172366b5c.png)

The chapters have a line height of 1.9em and the sections (and subsections) have a line height of 2.5em. This seems backward - I would expect chapters to be spaced at least as far apart as sections.

**Comment by azerupi** [comment]
It would make more sense that way, indeed. I will look into it, thanks for reporting :)

**Comment by JIghtuse** [comment]
@azerupi looks like it is enough to just swap these two `line-height`s to fix it. Will you accept this?
https://github.com/JIghtuse/mdBook/commit/4555adbcb0b86fb9b0b8b82b9bc99ff3733f11dd

Before:
![Before](http://i.imgur.com/HOB678G.png)
After:
![After](http://i.imgur.com/Y1ihMLy.png)

**Comment by azerupi** [comment]
@JIghtuse of course I would gladly accept a PR :)

I have tried some values and I think `2.5em` is a bit too much space for `.chapter` it looks weird. `1.9em` for `.section` and `2.2em` for `.chapter` looks better in my opinion. What do you think?

**Comment by JIghtuse** [comment]
@azerupi yep, `2.2em` for .chapter looks good for me too.
