### ISSUE TITLE
Slugify section anchors

### ISSUE THREAD

**Issue by dtolnay** [azerupi/mdBook#168]
For a section like `## Hello World` mdBook currently creates an anchor like `page.html#Hello World`. The anchor should be [slugified](https://github.com/SamyPesse/github-slugid) to be more URL-friendly: `page.html#hello-world`.

**Comment by azerupi** [comment]
This has been changed recently, [anchors are now url encoded](https://github.com/azerupi/mdBook/blob/master/src/theme/book.js#L59-L62).

A section like `## Hello World` should produce an anchor of the form `page.html#Hello%20World`. If that is not the case, it is a bug.

**Comment by dtolnay** [comment]
I would strongly prefer `#hello-world`. I don't like sharing or receiving links containing nasty urlencoded symbols because people want to know what they are clicking. [GitHub agrees](https://github.com/azerupi/mdBook#what-does-it-look-like).

**Comment by azerupi** [comment]
I think I have to agree too. 
It seems reasonable to change it to a more user-friendly form.
