### ISSUE TITLE
Possible to have code block with gray background, no syntax highlighting, and not run with rustc?

### ISSUE THREAD

**Issue by carols10cents** [azerupi/mdBook#179]
What I'm trying to do is get a `code` block that has the gray background that comes with:

```
.hljs {
   background: #f1f1f1;
}
```

(and the rest of the `.hljs` css too, probably) but *not* have any syntax highlighting applied, and also *not* have mdbook try and run the code block with `rustdoc --test`.

My use case is code blocks [like this](https://github.com/rust-lang/book/blame/master/src/ch09-01-unrecoverable-errors-with-panic.md#L34-L42) that are showing command line output:

```
$ cargo run
   Compiling panic v0.1.0 (file:///projects/panic)
    Finished debug [unoptimized + debuginfo] target(s) in 0.27 secs
     Running `target/debug/panic`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is
100', ../src/libcollections/vec.rs:1265
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/panic` (exit code: 101)
```

I've tried:

- Setting the language as `bash`, which uses the gray background, but since it's meant for bash *scripts* not bash *command line interactions*, it [confusingly](https://github.com/rust-lang/book/pull/134#discussion_r81432171) will [highlight arbitrary words like "in"](http://rust-lang.github.io/book/ch09-01-unrecoverable-errors-with-panic.html).
- Setting the language as `text`, [which turns off highlighting](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L39), but that also means that block doesn't get the `hljs` class since it technically didn't go through highlight.js.
- Setting the language as something nonexistent like `blah`, which has the same effect as `text`.
- Not setting a language at all, which *does* get me the grey background and lack of syntax highlighting, but `mdbook test` tries to run the contents as rust :(
- Setting the language to just `ignore`, which makes `mdbook test` ignore it as desired but has the same display without the grey background as `text`, `blah`, etc

Do you know of any other workarounds that would result in the behavior I'm looking for?

Alternatively, would you accept a PR that adds this (or similar) to highlight.css, that matches the [words in highlight.js's regex to not do syntax highlighting](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L39)? 

```
.language-no-highlight, .language-nohighlight, .language-plain, .language-text {
  display: block;
  overflow-x: auto;
  background: #f1f1f1;
  color: #6e6b5e;
  padding: 0.5em;
-webkit-text-size-adjust: none;
}
```

**Comment by azerupi** [comment]
I am not sure there is a workaround without touching mdBook's code.
There are actually two issues being reported here:

**1. Code blocks that don't go through highlight.js do not have any background color**

Modifying the `highlight.css` file directly is probably not that great. It is likely that it will get updated or replaced in the future. The best place to make this change would probably be [in mdBook's theme files](https://github.com/azerupi/mdBook/tree/master/src/theme/stylus/themes). There we can add a rule for codeblocks and a variable for every theme to change.

However, for consistency between `hljs` and `non-hljs` codeblocks, it would probably be better to override the background color that is set by `hljs` as well.

**2. `mdbook test` tries to run snippets that don't have a language specified**

This is more problematic & trickier, as the test command just invokes rustdoc on the chapters. I am not sure if there is a setting in rustdoc to be more conservative and only run the snippets explicitly tagged as Rust?

**Comment by carols10cents** [comment]
You're totally right that this is two separate issues, I was sort of trying to get at what I wanted from multiple directions :)

There's actually [one instance of `.hljs` in the theme files already](https://github.com/azerupi/mdBook/blob/master/src/theme/stylus/themes/base.styl#L103), does that make the solution proposed in 1) better or worse? ;)

Re: 2), I looked into `rustdoc` a little bit but didn't see any useful settings. I did get another workaround idea, though it doesn't work either: if I don't specify a language but then add hidden lines to start and end a block comment around the code, then rustdoc is able to compile it since it's treating unannotated code blocks as rust. mdbook only hides hidden lines in the resulting markup when the language is specifically marked as rust, and with the rust syntax highlighting of the block comment, the HTML generated by the code-hiding JS hides all the code since the `<span class="hidden">`s end the `<span class="hljs-comment">` instead. That is, if I try to do:

````
```rust
# /*
$ curl https://sh.rustup.rs -sSf | sh
# */
```
````

 `lines` ends up being:

```
[
  "<span class="hidden"> <span class="hljs-comment">/*
</span>",
  "$ curl https://sh.rustup.rs -sSf | sh",
  "<span class="hidden">
 */</span></span>"
]
```

Ahahaa hahah ha 😂😂😂😂😂 Foiled again!!!

**Comment by azerupi** [comment]
>There's actually one instance of .hljs in the theme files already, does that make the solution proposed in 

Indeed, it doesn't change the color though. 
To be honest, I don't think setting the color in the theme files is a horrible solution, it's probably the easiest one. I am just a little worried that down the line we will get issues reported because the hljs themes can't change the background color..

I will try to see if I can come with another idea, otherwise this fix is fine for me :)

> I looked into rustdoc a little bit but didn't see any useful settings.

I guess it would be a useful setting to have in rustdoc. I may or may not explore the possibility to make a PR if I find some time 😄

**Comment by carols10cents** [comment]
> I will try to see if I can come with another idea, otherwise this fix is fine for me :)

OOH I just had one more idea: what if book.js adds the `hljs` class to all `code` blocks after running `highlightBlock`?

**Comment by azerupi** [comment]
That is a good idea. It think it should work and it is probably a better solution than hard-coding the color in the themes. :)
