### ISSUE TITLE
Generate anchors when building instead of using JavaScript

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#204]
The Rust team uses a linkchecker tool, but since anchors are generated by JavaScript code, it can't check if those anchors are valid.

It would be a better solution to generate anchors when building the book. This would also be a step in the right direction for no-js people too.

rust-lang/rust#39856

**Comment by steveklabnik** [comment]
@azerupi so, two things.

1. you don't have cycles for mdbook right now, so we would have to implement this, right?
2. are you interested in changing the link generation to be the same as rustdoc?

I don't have strong feelings about the second bit, but would prefer to know before I go tweaking a ton of links 😄 /cc @frewsxcv

**Comment by azerupi** [comment]
> you don't have cycles for mdbook right now

I am not sure I understand what you are talking about.

>are you interested in changing the link generation to be the same as rustdoc?

I thought the anchor generation was changed to be the same as GitHub, is that not how rustdoc handles it? How would it differ from now?

I don't have strong preferences :)

**Comment by steveklabnik** [comment]
> I am not sure I understand what you are talking about.

Sorry, I meant "development cycles", in another PR you had said school meant you didn't have a ton of time to work on mdbook. I'm trying to make sure I respect your time here :)

> I thought the anchor generation was changed to be the same as GitHub, is that not how rustdoc handles it? How would it differ from now?

in the PR; I made this change, I left a comment next to the algorithm 😄

**Comment by azerupi** [comment]
Oh yes indeed, I have a lot of time-consuming projects preventing me to allocate much time to personal projects :confused: But I hope I can find some time here and there to make progress on some long standing issues here, fingers crossed :)

**Comment by steveklabnik** [comment]
Great! If you need maintenance help, now that rust is officially using mdbook, @frewsxcv and I might be willing to help, depending. Up to you of course!

**Comment by azerupi** [comment]
Actually, I have been meaning to talk to you about that :)
Considering my limited time and the fact that Rust now uses it, I would be ok with adding you (and eventually others) as contributors, or even move mdBook to an "organization" with multiple maintainers. I want to make sure that mdBook is reliable for the users and can grow without me being the limiting factor.

I am open for whatever would be best :)

**Comment by steveklabnik** [comment]
That'd be great! Is there any way you could make it to the next docs meeting? They're wednesdays at 20:00 GMT. Otherwise, we can schedule a specific time 😄

**Comment by azerupi** [comment]
Yes, I should be able to join :) It is on IRC right?

**Comment by steveklabnik** [comment]
Yes, `#rust-docs` on mozilla's IRC. I'll add an agenda item :)
