### ISSUE TITLE
<base href="../"> messes with anchor links

### ISSUE THREAD

**Issue by vberger** [azerupi/mdBook#211]
**Symptom:**

Go to http://azerupi.github.io/mdBook/cli/build.html, click on the title "The build command". You are redirected to the the introduction page. I'd expect this link to just be an anchor on the same page.

This is most likely due to the `<base href="../">` at the top of the page.

**Comment by azerupi** [comment]
@steveklabnik could this have been introduced by your PR #207? I am 90% confident this worked before. :)

**Comment by steveklabnik** [comment]
Ah, I think it was ☹️ 

I won't have time to look into this until tomorrow, but I'll fix it.
