### ISSUE TITLE
Request: Auto-Close sidebar on mobile

### ISSUE THREAD

**Issue by Anachron** [azerupi/mdBook#217]
On IOS 10.1 on latest Safari the Sidebar will open and close correctly, but mostly I want to auto-hide the sidebar as I want to focus on the content, rather than keep navigating.

**Comment by budziq** [comment]
Hi, 

This was fixed in https://github.com/azerupi/mdBook/pull/324

cc @azerupi

**Comment by Anachron** [comment]
Thanks!
