### ISSUE TITLE
Select the right pane when going to next/previous page

### ISSUE THREAD

**Issue by carlomilanesi** [azerupi/mdBook#235]
To read a text using only the keyboard, there must be commands to scroll a page. The up/down keys and page-up/page-down keys are OK, but they work only when the right pane is selected, by clicking on it. Left/right arrow keys allow to change page, but they also deselect the right pane. They shouldn't.
I should be able to read a whole book by pressing only the right arrow key and the down arrow key.

**Comment by azerupi** [comment]
Thanks for the issue report, this would indeed be a better behavior.

I think we could achieve this with the [html `tabindex` attribute](https://www.w3schools.com/tags/att_tabindex.asp), setting the right pane to index n° 1.
