### ISSUE TITLE
Allow unstable features for the unstable book

### ISSUE THREAD

**Issue by leonardo-m** [azerupi/mdBook#241]
The home page of the Unstable book shows an example with the box syntax. But if I try to run it in the page, the compilation fails because unstable features are not supported.

**Comment by steveklabnik** [comment]
The playpen takes a `&version=nightly` parameter onto its URL, so I believe that if we see `#[feature` in the code, we should tack that on.

**Comment by azerupi** [comment]
Considering we now support `rust,something` syntax. We could also take advantage of that and tag code blocks with an extra class `rust,nightly`. I am not sure what solution would fit better. :)

**Comment by steveklabnik** [comment]
Yeah, that idea would work as well. What's nice about the former approach is that it Just Works, but the latter version is nice because it gives you a bit more control.
