### ISSUE TITLE
Three digit numbering in ordered list has strange alignment

### ISSUE THREAD

**Issue by frewsxcv** [azerupi/mdBook#242]
https://doc.rust-lang.org/nightly/unstable-book/

<img width="310" alt="screen shot 2017-03-30 at 4 38 39 pm" src="https://cloud.githubusercontent.com/assets/416575/24525167/578ad1be-1567-11e7-85f9-c05d0b47c4c8.png">

**Comment by mthh** [comment]
I don't think it's a CSS issue but more something related to how the chapters and sections are prepared upstream in rust, specifically in the file [src/renderer/html_handlebars/helpers/toc.rs](https://github.com/azerupi/mdBook/blob/d7f38d08fd081c6cf45277197c560efe1eb9d8dd/src/renderer/html_handlebars/helpers/toc.rs)  (in your example @frewsxcv  chapters after 99 are put in a new "section" even if they are still chapters). I will try to propose a fix soon.
