### ISSUE TITLE
Alt-left does not go back

### ISSUE THREAD

**Issue by samlh** [azerupi/mdBook#249]
The left/right key handlers block the desired behavior of Alt-left/right to go forwards or backwards in the browser history.

Chrome Version 57.0.2987.133

Tested on https://doc.rust-lang.org/nightly/book/second-edition/ch15-01-box.html

**Comment by crazymerlyn** [comment]
This seems to have been fixed.

**Comment by budziq** [comment]
Hi,

this has been fixed a while ago in master.

cc @azerupi
