### ISSUE TITLE
`mdbook build` flag that doesn't implicitly create files and errors if bad path in SUMMARY.md

### ISSUE THREAD

**Issue by frewsxcv** [azerupi/mdBook#253]
For rustc's CI, we set the filesystem to be mostly read-only. If a rustc docs contributor accidentally adds in an invalid path, [we get these obscure read-only errors](https://github.com/rust-lang/rust/pull/40290#issuecomment-294137045) because mdbook is trying to create a file even though we don't want it to. It'd be helpful if there was a `mdbook build` flag like `--nocreate` or `--strict` that doesn't attempt to create files from SUMMARY.md if they don't exist and instead results in a build error.

Does this sound alright? If so, I can implement this.

**Comment by steveklabnik** [comment]
Seems good to me.

**Comment by azerupi** [comment]
Yes, sounds good! 
I am not sure about the exact flag to use, `--strict` definitely sounds too generic. `--nocreate` could be ok, even though it does not clearly show that it only affects the creation of source files. Anyway, this is just a small thing that can be discussed and changed when the PR is ready :)

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/azerupi/mdBook/issues/254
