### ISSUE TITLE
Styling of inline code item has same styling as inline code item w/ hyperlink

### ISSUE THREAD

**Issue by frewsxcv** [azerupi/mdBook#261]
mdbook styles these identically:

```
`foo`
```

```
[`foo`](https://foo.com)
```

which isn't great if you want the user to know that the second item is a link. Here's how github styles them:

`foo`

[`foo`](https://foo.com)

**Comment by budziq** [comment]
Should it not be closed due to https://github.com/azerupi/mdBook/issues/289?

**Comment by azerupi** [comment]
Yes, it should :)
