### ISSUE TITLE
Indentation of `#` hidden code

### ISSUE THREAD

**Issue by dtolnay** [azerupi/mdBook#281]
In https://github.com/brson/rust-cookbook/pull/107 we discovered that mdBook is indenting hidden code by one space when expanded.

```rust
a
# b
```

... turns into:

```rust
a
 b
```

This is not the behavior of rustdoc. For example look at [this standard library example](https://github.com/rust-lang/rust/blob/1.17.0/src/libstd/thread/local.rs#L124) and then click through on the "Run" button [here](https://doc.rust-lang.org/std/macro.thread_local.html#syntax). The line is not indented by one space.

**Comment by steveklabnik** [comment]
Interesting; I thought I copied rustdoc's behavior here exactly.
