### ISSUE TITLE
Move from try! to the questionmark

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#286]
A lot of code that hasn't changed in a while is still using `try!` but it often hurts readability. I would like to move away from `try!` and use the new question mark operator.

[rustfmt seems to have an option for that](https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#use_try_shorthand), so I suppose this is just a matter of adding the option, running rustfmt on the code and verifying that nothing broke. 😄

**Comment by budziq** [comment]
I would like to work on that :)

**Comment by budziq** [comment]
Wow rustfmt with mdbook's rustfmt.toml (and `use_try_shorthand = true`
) makes **a lot** of additional changes https://github.com/budziq/mdBook/commit/1cc19e4b3eedd8a10895908a0a998bd5e0589a84.
Should I limit the changes to only to `try!` related or is a full PR ok?

@azerupi

**Comment by azerupi** [comment]
It has been a long time since I have run rustfmt on the code, so that should be expected. A full PR is ok,  I can manage that :wink:
