### ISSUE TITLE
unfriendly build.rs errors for stylus

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#293]
Hi,

As mentioned on #292
the build.rs output when of node / npm / nib / stylus is missing are pretty cryptic.

Would you be interested in a PR to make it more friendly?

Moreover, I guess that pulling error-chain as a dependency is out of the question?

**Comment by azerupi** [comment]
>Would you be interested in a PR to make it more friendly?
 
Of course! I will never say no to a PR that improves error messages. :+1: 

>Moreover, I guess that pulling error-chain as a dependency is out of the question?

It is not, I have actually considered using it for some time but never had the time to take a closer look at it. I've heard many people praise its usefulness and simplicity so I am willing to try it out. If you want to pull it in as a dependency I am fine with it.
