### ISSUE TITLE
generating css from stylus fails on Windows

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#294]
Hi,

I wanted to test my code fixing https://github.com/azerupi/mdBook/issues/293 
And when testing the solution on Windows I have noticed that 
`cargo build --features=regenerate-css` will always fail (with or without my changes).
It looks like Rust `Command` PATH finding is is broken https://github.com/rust-lang/rust/issues/37519 or at least works differently than expected. 

Namely stylus is represented on Windows as stylus.cmd while `Command::spawn` will append ".exe" but does not test with other executable extensions like cmd, thus `Command::new("stylus")` will expand to `Command::new("stylus.exe")` instead of `Command::new("stylus.cmd")`. Fortunately explicitly stating .

This should be relatively easy to workaround with `#[cfg(windows)]`
Nevertheless, the CI probably should be updated to test if stylus works too.

**Comment by azerupi** [comment]
Thank you for the report. 
As I have no Windows machine, support for it is sometimes lagging a little behind. I rely very strongly on AppVeyor, and contributions from Windows users for that part. 

> Nevertheless, the CI probably should be updated to test if stylus works too.

Indeed, we could add the build script to the CI to assure it always works.
