### ISSUE TITLE
Print the Serving message as a link

### ISSUE THREAD

**Issue by dtolnay** [azerupi/mdBook#299]
```
$ mdbook serve

Serving on localhost:3000

Listening for changes...
```

If instead you print "Serving on http://localhost:3000", most terminals will print it as a clickable link. :wink:

**Comment by azerupi** [comment]
Nice, I didn't know that :)

**Comment by budziq** [comment]
Hi I've made a PR for it but I guess that `-o` option would be desirable for this usecase
