### ISSUE TITLE
Suport spaces indentation in SUMMARY.md

### ISSUE THREAD

**Issue by LuisAyuso** [azerupi/mdBook#309]
Hi there,

To nest chapters in the Summary, the line must begin with a tab character. Unfortunately I am used to turn tabs into spaces, and all of my editors are configured in this way.

How difficult would it be to implement this?
Can you describe the location and procedure currently in use?
 maybe I can find the time to implement it.

Cheers.

**Comment by azerupi** [comment]
Are you sure spaces are not supported? They should be, and if it is not the case it is a bug! :)

The code parsing the summary and more specifically the code for the indentation can be found [here](https://github.com/azerupi/mdBook/blob/master/src/parse/summary.rs#L128).  Overall, the whole summary parsing would need to be rewritten IMHO. I have tried multiple times to rewrite it with [nom](https://github.com/Geal/nom) but I couldn't figure out how to make it work like I wanted. I will probably try again in the near future!

**Comment by LuisAyuso** [comment]
Hi again,
I tried again and it is working. I must have done something wrong the last time. 
Thanks for the reply.
