### ISSUE TITLE
Include`custom.js` file if it exists

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#311]
Hi similarly to https://github.com/azerupi/mdBook/issues/178

I would be interested in adding support for "custom.js" to be loaded if one exists. This two would let us stop needing to pull index.hbs (some minimal js there) and full book.css into rust-cookbook.

**Comment by azerupi** [comment]
Good idea, it should not be too difficult to add this to #287

**Comment by budziq** [comment]
Thanks :) . Issues such as https://github.com/rust-lang/book/issues/55 could be implemented trivially downstream without any modifications to MDBook. If you don't feel like implementing it I'll gladly add it once https://github.com/azerupi/mdBook/pull/287 gets merged.

**Comment by earlAchromatic** [comment]
This doesn't work for remote urls. Say I want to import some external 3rd party lib? I should be able to do: 

```
[output.html]
additional-js = ["./theme/custom.js", 'https://somedomain.com/dist/external.v1.js']
```
and have it add:

```
<script src="https://somedomain.com/dist/external.v1.js">
```

Even better if I can add notation for `async` and `defer` attributes.

Unless there is an existing mdBook way to do this?

**Comment by ehuss** [comment]
You can include any script tags you want in `head.hbs`, see https://rust-lang.github.io/mdBook/format/theme/index.html.

**Comment by earlAchromatic** [comment]
Got it thanks!
