### ISSUE TITLE
How to handle breaking releases, and how can we help users?

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#327]
Current master has breaking changes to the configuration file. I expect there will be more breaking changes in the future as we improve and refactor mdBook. So we can't guarantee stability. However, users might automate deployment of books through CI and we don't want to break their deployments every time we make a breaking release! 

So, can we figure out a way to pin CIs to a specific non-breaking version range of mdBook (like cargo does) so that the user can choose when to update to the breaking release? 

Ideally we would need to come up with a solution that all the users can easily implement in Travis (or other CIs). Post it on the different forums and projects known to use mdBook and give some time to the users to migrate. Then we can release the `0.1.0` breaking release.

This issue is particularly relevant for the different books in the Rust community (TRPL2, Cookbook, ...), I'm not sure how they handle deployments currently?

@steveklabnik @budziq @frewsxcv 

Feel free to tag anyone who might have an interest in this discussion.

**Comment by budziq** [comment]
`cargo install` supports `--vers` flag also for binaries
Basically we can endorse all users to pin their CI to specific mdbook binary version like below:
`cargo install mdbook --vers 0.0.22`

Then changing version of mdbook with which the artifacts are built in CI would have to be conscious decision on user side. And if they would like to benefit from bugfixes and new features they would have to follow some porting guideline (possibly a trivial 1-4 liner in docs).

cc @brson

**Comment by azerupi** [comment]
Beginning with the `0.1.0` which should be the next release, we will bump the minor version every time we make a breaking release. I just tested and cargo supports `cargo install mdbook --vers "0.0.*"` so I think we should start by making users use that instead of just any version.

**Comment by budziq** [comment]
`cargo install mdbook --vers "0.0.*"` (or any other incomplete semver triple) produces a depreciation warning from cargo
```
warning: the `--vers` provided, `0.0.*`, is not a valid semver version

historically Cargo treated this as a semver version requirement accidentally
and will continue to do so, but this behavior will be removed eventually
```
since https://github.com/rust-lang/cargo/issues/3321 cargo depreciated using --vers with "semver requirements" (as in lib requirement) in favour of specific "semver versions".

Imho it is a shame as it was a nice feature.

**Comment by steveklabnik** [comment]
> Basically we can endorse all users to pin their CI to specific mdbook binary version like below:
cargo install mdbook --vers 0.0.22

Yes, this is what I'd suggest as well.

**Comment by azerupi** [comment]
>since rust-lang/cargo#3321 cargo depreciated using --vers with "semver requirements" (as in lib requirement) in favour of specific "semver versions".

Oh so you can't specify semver ranges for binary install? That's a bummer...

**Comment by azerupi** [comment]
Ok, we should start pinging projects that use mdBook to warn them of an 'imminent' breaking release and that if they deploy with CI they should pin the version number. If you know of any projects using mdBook, please let me know here!

- [x] [Rust Cookbook](https://github.com/brson/rust-cookbook) is already using a pinned version.
- [ ] [The Rust Programming Language]() is using master.
- [ ] [Bindgen](https://github.com/servo/rust-bindgen) is using an unpinned version.
- [ ] [IntermezzOS](https://github.com/intermezzOS/book) is using an unpinned version.
- [ ] [Redox](https://github.com/redox-os/book) not sure if they automatically deploy?
- [ ] [Lumol](https://github.com/lumol-org/lumol) is using an unpinned version.
- [ ] [Clap](https://github.com/kbknapp/clap-book) not sure if they automatically deploy?
- [ ] ... ?

**Comment by steveklabnik** [comment]
TRPL is using a pinned version, not master: https://github.com/rust-lang/rust/blob/master/src/tools/rustbook/Cargo.toml#L11

I am happy with intermezzOS automatically updating, no need to warn me 😄

**Comment by budziq** [comment]
Hi these are the ones I know of:
- [ ] [gentle-intro](https://github.com/stevedonovan/gentle-intro) - not sure if they deploy automatically
- [ ] [wayland-rs](https://github.com/Smithay/wayland-rs) - uses unpinned version
- these two are owned by Steve so I post them just for refference ;)
    - [ ] [nomicon](https://github.com/rust-lang-nursery/nomicon) - uses unpinned version
    - [ ] [reference](https://github.com/rust-lang-nursery/reference) - uses unpinned version

**Comment by azerupi** [comment]
> TRPL is using a pinned version, not master

Good to hear, I suppose that applies to all the books in the Rust org? :)

**Comment by steveklabnik** [comment]
Yes, the same thing is used for all of the ones on doc.rust-lang.org.

**Comment by azerupi** [comment]
I have made a PR to cargo rust-lang/cargo#4229 to add semver ranges to `cargo install --vers`. Once this is merged we can start to recommend users to pin the version of mdBook like this

```
cargo install mdbook --vers "~0.0.22"
```

It should already work with Cargo right now (with a deprecated warning) but if the PR gets merged we are guaranteed that this behaviour will stay and that the deprecated warning will go away in future releases.

**Comment by azerupi** [comment]
I have opened an issue in each repository listed here. Maybe I should also make an announcement on the users forum?

Another thing that needs to be done is to mention the version pinning for CI scripts in the readme. This will hopefully allow new projects to pick up the good habit from the start.

**Comment by budziq** [comment]
> I should also make an announcement on the users forum?

We have a users forum :smile_cat:? How can one find it?

> Another thing that needs to be done is to mention the version pinning for CI scripts in the readme. This will hopefully allow new projects to pick up the good habit from the start.

Good idea. We have to update the docs anyway for 0.1.0 release

**Comment by azerupi** [comment]
Well I was talking about the [Rust user forum](https://users.rust-lang.org/) :smile:

**Comment by budziq** [comment]
> Well I was talking about the Rust user forum :smile:

Also a good idea. https://www.reddit.com/r/rust/ is also a popular place for rustaceans to visit

**Comment by vberger** [comment]
I have a question regarding this, how does 
```
cargo install mdbook --vers "^0.0.22"
```
interact with
```
cargo install-update -a
```
that I use in my CI ?

**Comment by budziq** [comment]
@vberger 
`cargo install-update -a` does not seam to be a standard cargo command?
so  I can't really say. do you use some helper crate to get this command?

**Comment by vberger** [comment]
yes: https://github.com/nabijaczleweli/cargo-update

This allows me to use the travis cache to avoid rebuilding mdbook & friends every time (this tends to make the builds timeout, as some dependencies are quite long to compile), while still keeping them up to date.

I was just asking in case you knew, but I should probably ask them directly.

**Comment by budziq** [comment]
@vberger I've tested the `cargo-update` crate with your command. 
It forces installation of newest mdbook available via crates.io.

So basically when mdbook v0.1.0 is suddenly released yo would have to call
`cargo install mdbook --vers "^0.0.22" --force` (to install the older version if newer is installed)
right after `cargo install-update -a` and prior to `mdbook build`.

But I understand that travis will have to build mdbook at least once unless the mentioned travis cache is smarter than I think ;).

**Comment by azerupi** [comment]
> how does `cargo install mdbook --vers "^0.0.22"` interact with `cargo install-update -a`

`cargo install mdbook --vers "^0.0.22"` will install the latest version compatible with `0.0.22` in a semver sense. As far as I know, `cargo install-update` doesn't offer any flag to specify a version so it will always update to the latest version. Maybe they would consider adding this feature? It's worth opening an issue on their repo.
