### ISSUE TITLE
close theme selection popup after interaction

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#330]
Hi,

I find it slightly irritating that theme selection popup stays open until the brush icon is clicked again (it is especially vexing in case of mobile browser).

I would suggest to close the theme selector popup after:

1. user selects the theme - this might not be always desirable (but it would find it as a nicer default)
2. user interacts outside of the popup (click/swipe/pan) - imho this would be always desirable.

note to self: most likely [this](https://stackoverflow.com/questions/152975/how-do-i-detect-a-click-outside-an-element/3028037#3028037) should do the trick for (2.)

What are your thoughts?

**Comment by azerupi** [comment]
I'm okay with both. I've found it to be an annoyance as well, just not enough to try to solve it.. For mobile it is indeed a very desirable behavior. :+1:
