### ISSUE TITLE
code snippet font size a little smaller in FF

### ISSUE THREAD

**Issue by asgs** [azerupi/mdBook#341]
Hello! On Firefox, the font size of the section where the code snippets are shown is smaller than the rest of the text. Please check the [FF Screenshot](https://user-images.githubusercontent.com/833190/27252205-e2fbae3e-5375-11e7-8c11-5b23c47db220.png)

On Chrome, it's better as the size seems to be consistent with the rest of the content.

I'm not sure how a size of 0.875 em makes that noticeable a difference in these two browsers. Code snippets are as important as the rest of the text in the tutorial, so it's not ignorable.

**Comment by budziq** [comment]
closed by #445
