### ISSUE TITLE
Make MathJax optional

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#347]
Basically like in case of ACE.
MathJax is a large dependency that might be seldom required 

Additionally it blocks offline reading https://github.com/rust-lang/book/issues/711 due to how it is incrementally loaded from cdn.

It would be preferable to have MathJax as an optional dependency with key in the book.toml.

~~blocked on https://github.com/azerupi/mdBook/pull/335 - will need to wait until curent hbs_renderer refactor is finished.~~

**Comment by Michael-F-Bryan** [comment]
#335 just got merged, so it should no longer be blocking this.

**Comment by budziq** [comment]
> #335 just got merged, so it should no longer be blocking this.

Yup ;) I'll look into this issue later on.
