### ISSUE TITLE
Extract MdBook binary commads to separate files

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#348]
As discussed on https://github.com/azerupi/mdBook/pull/332#issuecomment-310618707

Separate MdBook binary commands should be separated to own modules and files.

Additionally whole `watch` module would be conditionally compiled with `#[cfg(feature = "watch")]`

**Comment by azerupi** [comment]
I think, but I would have to check, that it is possible to move the subcommand related Clap code to the new files too. This would put everything related to a subcommand in one file.
