### ISSUE TITLE
init --theme

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#35]
The `mdbook init --theme` command should copy all the theme files over to src, so that the user can modify them without having to start from scratch.

I am not sure if it should also do the rest of the normal init, or not

**Comment by azerupi** [comment]
@kbknapp sorry to bother you. 

For this feature I would like warn users and ask them if they want to continue. Something like this:

```
Copying the theme to 'src/theme' could overwrite files already present. 
Are you sure you want to continue? (y/n)
```

Is that functionality in `clap`, or do you know an easy way of doing this? :)

**Comment by kbknapp** [comment]
No worries :smile:

There isn't anything like a `confirm()` in `clap` (although that's not a bad idea!).  I've found it's usually also a good idea to give the user a chance to skip the confirmation if they know what they're doing (by adding `--noconfirm` or `--force`, etc.)

The best way to do this is:

```rust
use std::io::{self, Write, Read};

fn main() {
    let m =   // everything normal - just add an arg that uses --init, and one for skipping such as --noconfirm
    .get_matches() ;

    if m.is_present("init") && !m.is_present("noconfirm")  {
        if !confirm() {
            println!("exiting...");
            ::std::process::exit(0);
        }
    }
}

fn confirm() -> bool {
    print!("Copying the theme to 'src/theme' could overwrite files already present.
Are you sure you want to continue? (y/n): ");
    io::stdout().flush().unwrap();
    let mut s = String::new();
    io::stdin().read_line(&mut s).ok();
    match &*s.trim() {
        "Y" | "y" => return true,
        _         => return false
    }
}

```

**Comment by azerupi** [comment]
Nice! Thank you for that :)

> There isn't anything like a confirm() in clap (although that's not a bad idea!).

That would be a neat thing to have ;)

> Also, I've vote :+1: on doing all the init when a user does init --theme. I'd find it confusing to run...

I agree, the only reason I was hesitating is that you may want to copy the theme in an already existing project. And at that moment you don't want `init` to mess up what you already have. 

But I it's a better idea to implement `init` so that it does not mess up an existing project when runned.
