### ISSUE TITLE
Logging to stdout seems to be disabled

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#358]
Since some time, mdBook doesn't log anything to stdout anymore. Users don't get any feedback from mdBook, which is not good...

Related to #355

**Comment by budziq** [comment]
Well it is not really disabled we just don't log messages on `Error` level which are displayed by default. If we set `RUST_LOG=info` or `debug` we see some additional logs. It depends what you would like to achieve.

Cargo for instance uses dual logging system. `env_logger` like mdBook does for its backend/library part (that is controlled by `RUST_LOG` env var). And `termcolor` based colored  output to stdout for the binary frontend app that is controlled by `--verbose` and `--quiet` cmd switches.

We can either:
- emulate cargo's split logging system
- raise the default visible loggin level to `info`
- use println / termcolor where we want guaranteed output to stdout.

but firstly we would need to know which logs would need to be shown by default.

**Comment by azerupi** [comment]
>Cargo for instance uses dual logging system.

Interesting. I assume this is to split the output into messages for the devs and messages for the users, which is nice. We could go that route if it doesn't add a lot of complexity. Otherwise we should set the logging level to info I think, and make sure that all the messages for ìnfo`, `warn` and  `error` are directed at users. We can keep `debug` and `trace` for development purposes.

Having coloured output would be a nice addition too.

**Comment by budziq** [comment]
Having split logging would certainly add complexity [cargo seams to prefer logging to user](https://github.com/rust-lang/cargo/search?utf8=%E2%9C%93&q=warn&type=) (with several variants of their `shell.warn` as opposed to seldom used `warn!`).

I would go with `info` bumping the level to `info` and see how do we like it. Also colored output is pretty trivial to add with https://github.com/seanmonstar/pretty-env-logger (I helped clean its docs some time ago).
