### ISSUE TITLE
playpen files: Generic parameters aren't parsed ?

### ISSUE THREAD

**Issue by Songbird0** [azerupi/mdBook#365]
Hi!

When I use `{{#playpen my/rust/file/path}}`, all generic parameters, like `<i32>`, are missing.

I tried this code (in my playpen file):
```rust
struct List(Vec<i32>);
struct Other(Vec<i32>);
```
I expected to see this happen: When my playpen file is merged, generic parameters are presents.

Instead, this happened: The HTML page prints:
```rust
struct List(Vec);
struct Other(Vec);
```

## Meta

`mdbook --version`: mdbook v0.0.22

Regards.

**Comment by budziq** [comment]
Hi @Songbird0 this is most likely https://github.com/azerupi/mdBook/issues/345 and was solved by in git master but not yet released to crates.io.

Would you be willing to test against git master (there are some other breaking changes so do not be alarmed ;) )?

**Comment by Songbird0** [comment]
​Hi!

Sorry for duplication.

Would you be willing to test against git master (there are some other
breaking changes so do not be alarmed ;) )?​

​Done! It's all right. My generic parameters are printed in `mdbook
v0.0.22-pre` version.​ Thanks!


Regards.

**Comment by budziq** [comment]
> Sorry for duplication.

no problem :) be sure to comeback
