### ISSUE TITLE
links to next page should set rel="next"

### ISSUE THREAD

**Issue by matthewleon** [azerupi/mdBook#375]
I was surprised, when reading The Rust Programming Language (https://doc.rust-lang.org/book/second-edition/ch01-00-introduction.html), that the keyboard shortcuts I normally use to move through the pages in a document weren't working properly. I believe that simply setting the `rel` attribute to "next" on the next page arrow button should fix the problem.

**Comment by budziq** [comment]
Hi @matthewleon 

Mdbook already allows for next/ prev page navigation with left/right arrow.
Could you tell what exact browser are you using and which keyboard shortcuts do you mean (key combination and desired effect).

I'm not even a part time webdev by trade so please bare with me :)

**Comment by azerupi** [comment]
I think this has been fixed in master recently by #228 but is not yet released. We are currently waiting to make a new release because some projects don't pin their mdBook version in their CI deployment scripts, and we want to give them some time to fix that before we release (see #327)

**Comment by matthewleon** [comment]
> I think this has been fixed in master recently by #228 but is not yet released.

Looks good, thanks. Closing.
