### ISSUE TITLE
The emph(*) tag does not seem to properly work with a non-english text with parentheses

### ISSUE THREAD

**Issue by rinthel** [azerupi/mdBook#376]
Hi, I'm trying to translate the second edition of the Rust book into Korean.
And I found a strange behavior when I use emph tags.
While the english text with parentheses, something like 'Gabarge Collector(GC)',
was well emphasized by using one * tag, like *Gabarge Collector(GC)*,
its Korean translation version of the text '가비지 콜렉터(GC)' wasn't
emphasized with just one * tag. *가비지 콜렉터(GC)*
Instead, * symbols explicitly come out of HTML documents.
Currently I am binding the text with two tags, one for the previous words and
the other for the words inside parentheses.
Is it some kinds of a bug? Or how can I fix it correctly to use just one * tag?
Thanks for your help!

**Comment by budziq** [comment]
hi @rinthel 

this us most likely problem with our markdown renderer backend https://github.com/google/pulldown-cmark

could you post a minimal reproducing snippet ideally in escaped markdown section?

<pre>
```markdown
some *text* some more text
```
</pre>

I'll try to look into it when I'm on pc next week.

**Comment by rinthel** [comment]
Thanks, here is a example:

<pre>
```markdown
In C++, this pattern of deallocating resources at the end of an item's
lifetime is sometimes called *Resource Acquisition Is Initialization (RAII)*.

C++에서는 이렇게 아이템의 수명주기의 끝나는 시점에 자원을 해제하는 패턴을
종종 *자원 습득이 곧 초기화 (Resource Acquisition Is Initialization, RAII)* 라고
부릅니다.
```
</pre>

Please notify me for any other thing I can do. Thank you!

**Comment by budziq** [comment]
Hi,

I am having trouble in reproducing this problem on latest mdbook v0.0.22 from crates.io The provided snippets is rendered as:
![rendered_em](https://user-images.githubusercontent.com/221000/28009180-c8911c68-655a-11e7-9cb0-5e5811d75355.png)
I'm no expert on Korean typography but the text looks properly slanted between the `*` marks. And the html source of the rendered document puts the \<em\> tags in proper places. 
![em_source](https://user-images.githubusercontent.com/221000/28009189-cea4aade-655a-11e7-8a84-df6aa6de027d.png)

Also I've played a little with ASCII and nonASCII charactes parentheses and `*` and I was not able to find any case which would work incorrectly.

Please tell me which version of mdbook are you using and maybe post how does the text render with html source and how would you like it to render

**Comment by rinthel** [comment]
Thank you for your kind report, and you produce what I expect exactly, so maybe I wrote a wrong code or my mdbook version was too old.
I would like to check my problem again when it's possible, and I'll report what was wrong. Thank you so much!

**Comment by budziq** [comment]
If there are any further problems, do not hesitate to ask. There might be a real bug somewhere in there, so it is worth double checking checking on your side.

**Comment by rinthel** [comment]
After several experiments, I found how to reproduce what I saw.
Consequently, it's not about the ascii and non-ascii code,
but about the closing asterisk right after closing parenthesis without following whitespace.
here is my experimental code:
<pre>
```markdown
some *text* here

some*text*here

some *(text)* here

some*(text)*here

some*(text)* here

some *(text)*here

some (*text*) here

some(*text*)here

*some (text)* here

*some(text)*here

*(some) text* here

*(some)text*here
```
</pre>

And its results:

---

some *text* here

some*text*here

some *(text)* here

some*(text)*here

some*(text)* here

some *(text)*here

some (*text*) here

some(*text*)here

*some (text)* here

*some(text)*here

*(some) text* here

*(some)text*here

---

And, I notice that the results produced by mdbook and those generated by
github markdown in this issue board are same. So, I guess that while
the markdown parser used in the mdbook was well-implemented
according to the markdown grammer spec, the results what I saw were
the limitation of markdown grammer itself.

Thank you for your kind help, and I would be more careful when I use asterisks
and parentheses simultaneously. :)

**Comment by budziq** [comment]
@rinthel I would not exactly state that githubs markdown is 100% compliant with the spec (neither is pulldown-cmark at the moment). So if one of your failing usecases should work under the [commonmark specification](http://spec.commonmark.org/0.27/) then I would open an issue in https://github.com/google/pulldown-cmark. I am closing this issue for now :)
