### ISSUE TITLE
Add tooltips to code buttons

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#388]
![image](https://user-images.githubusercontent.com/7647338/28922393-4f1ae716-785a-11e7-9fa6-3db5879bdf9c.png)

Buttons on code blocks do not currently have tooltips explaining what they do. It would be great to add tooltips with a very short explanation of what the buttons do (couple of words) when hovering over them.

**Comment by budziq** [comment]
Also any other icon like print/hamburger/paint brush could use a tooltip

**Comment by budziq** [comment]
Ha I stand corrected, the print button already has a tooltip with the "title" attribute
We could easily implement the tooltips using the native browser tooltip like this 

![tooltip](https://user-images.githubusercontent.com/221000/28923469-78840bec-785e-11e7-93c8-c4efad3d7f67.png)
```html
<i class="fa fa-play play-button" title="Run the code"></i>
```

**Comment by azerupi** [comment]
Yes :)
This is a really trivial addition. Good first issue for new contributors, if not too easy. :)

**Comment by budziq** [comment]
Well we might want to handle separately the expand/collapse code button so this issue would not be super trivial ;)

**Comment by azerupi** [comment]
I guess trivial is relative, but by pointing out to new contributors that buttons are inserted in the page through JavaScript [here](https://github.com/azerupi/mdBook/blob/master/src/theme/book.js#L176-L201). I am confident that anyone can pick up this issue without much difficulties. 😄

**Comment by budziq** [comment]
hmm we can even post [TWIR](https://users.rust-lang.org/t/twir-call-for-participation/4821/111). We met with great success in rust-cookbook when posting there :)

**Comment by projektir** [comment]
With the work in #338, there is now a new reset button which should also have a tooltip:
![f9wn5ec](https://user-images.githubusercontent.com/16269746/28999766-2d5ce18c-7a22-11e7-990f-5fa5e056b59a.png)
