### ISSUE TITLE
`mdbook test`: Compilation error has been skipped.

### ISSUE THREAD

**Issue by Songbird0** [azerupi/mdBook#391]
Hello there!

The `mdbook test` command doesn't inform me about the compilation error.

I tried this code:

```markdown
<!-- in foo.md file -->
# Foo

{{#playpen source/foo.rs}}
```

```rust
// in foo.rs file
fn main(){
    let foo = "hello world!".to_owned();
    let bar = foo; // move
    println!("{}", &foo); // doesn't compile.
    // compilation error will be skipped.
}
```

I expected to see this happen: The `mdbook test` command prints the `rustc` error.

Instead, this happened: `mdbook test` displays this:

```
[*]: Testing file: "${PWD}/src/chapter1/foo.md"
```

No error displayed.

When I'm trying to compile and run my sample via my book, the compilation error is here:

![image](https://user-images.githubusercontent.com/13397428/28996064-9ae55e84-79f8-11e7-9587-06c42ea83153.png)

->

![image](https://user-images.githubusercontent.com/13397428/28996070-ad1478e2-79f8-11e7-92e4-fc6edcf42275.png)

mdbook version: `mdbook v0.0.22-pre`

Regards.

**Comment by budziq** [comment]
Yep I can confirm it in master. This is due too `preprocess::links::replace_all` (where we expand the playpen links) called only inside `HbsRenderer::render_item`which is not used in `mdbook test`. We will need to further separate the link expansion/preprocessing from rendering.
