### ISSUE TITLE
If a request to the playground errors, no indication is ever shown as such in the UI

### ISSUE THREAD

**Issue by carols10cents** [azerupi/mdBook#392]
Right now, if you view TRPL locally via `rustup doc --book`, the playground requests [will all fail because of the playground's current CORS settings](https://github.com/integer32llc/rust-playground/issues/194). 

But even if those worked, if you didn't currently have internet acccess and tried to click the play button from the local copy of the book, the playground requests would also fail.

In these situations currently, the markup just shows "Running..." forever because [there's only a `success` handler for the request](https://github.com/azerupi/mdBook/blob/35a447d08aaf6ef7308ebf461ea9cb9645e729d4/src/theme/book.js#L323-L335). It would be nicer if an error message was displayed if something went wrong with the request.

**Comment by azerupi** [comment]
We should definitely notify the user on error. Thanks for the report!

Have the CORS settings been changed recently? I could swear it was working locally in the past.

**Comment by projektir** [comment]
I've been seeing the CORS stuff, too. It was definitely working locally last time I worked with **mdBook**, though, so I figured it was just something up with my setup at the time.

**Comment by carols10cents** [comment]
The playground recently changed over to https://github.com/integer32llc/rust-playground, which is a reimplementation from scratch. It's useful info for @shepmaster to know that the old playground allowed those requests, thank you!

**Comment by budziq** [comment]
Nevertheless we should handle error conditions such as these. This should be pretty trivial with adding `error` callback to book.js line 334 and possibly `timeout` value too.
