### ISSUE TITLE
`no_run` and other playpen parameters not added to <code> classes if space separated

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#397]
The additional playpen parameters (in case of inline markdown rust code) are not added to class list of generated playpen <code></code> if separated by whitespace from the `rust` language specifier.

<pre>
```rust, no_run
...
</pre>

this should result in 
```
<code class="language-rust no_run">...</code>
```

---

edit: 
following works
<pre>
```rust,no_run
...
</pre>
while the space separated does not
<pre>
```rust, no_run
...
</pre>

edit2: This feature works somewhat outside of CommonMark spec. `rust,no_run` is treated as `language-rust,no_run` by the virtue of not containing any whitespace. CommonMark spec does not specify any mandatory behavior for the reminder of the codeblock header (which pulldown-cmark eagerly utilizes dropping everything after the whitespace) 

TLNR: I learnt something new today ;)

**Comment by budziq** [comment]
The no_run,ignore,should_panic annotation is already eagerly used by several mdbooks and markdown preprocessors. The best I can think of to make the behavior more consistent is to preprocess the markdown codeblock headers in order to get rid of whitespace. Pushing non spec conformant changes to pulldown-cmark is not realistic nor desirable.

**Comment by azerupi** [comment]
>make the behavior more consistent is to preprocess the markdown codeblock headers in order to get rid of whitespace.

Sounds good to me, preprocess to remove withespace, feed to pulldown-cmark, post-process to replace commas by spaces.

**Comment by budziq** [comment]
Right. Possibly another converter could be added to `utills::render_markdown` along the lines of `EventQuoteConverter`
