### ISSUE TITLE
run rustfmt on the repository

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#398]
The codebase could use some minor cleanups:
We should run `rustfmt` on the codebase.

It is a nice introductory task to get someones feet wet in the project with some light mentoring.

please use [rustfmt-nightly](https://crates.io/crates/rustfmt-nightly) crate for the job

**Comment by azerupi** [comment]
The new version of rustfmt that only runs on nightly at the moment. I heard the style changed quite a bit for the better.

**Comment by budziq** [comment]
Good idea. I've updated the description

**Comment by budziq** [comment]
merged
