### ISSUE TITLE
run fix clippy warnings in the repository

### ISSUE THREAD

**Issue by budziq** [azerupi/mdBook#399]
The codebase could use some minor cleanups:
We should run `clippy` on the codebase and fix its warnings.

It is a nice introductory task to get someones feet wet in the project with some light mentoring.

**Comment by jacwah** [comment]
Is this resolved by #466?

**Comment by azerupi** [comment]
Was that all the clippy warnings?
I am surprised we got so few warnings on the whole code base 😲

**Comment by jacwah** [comment]
#466 fixes all but the two warnings I listed. I'm not sure what to do about those, so would love some feedback :)

**Comment by azerupi** [comment]
> I'm not sure what to do about those, so would love some feedback

I would mark them as allowed (or ignore? whatever clippy understands) on a case by case basis. We should avoid disabling the warning on the whole code base and evaluate every instance as they come.
