### ISSUE TITLE
No links in .md but visible links in .html

### ISSUE THREAD

**Issue by hazama-yuinyan** [azerupi/mdBook#405]
Hi! Above all, I don't know whether the topic would fit here, so __forgive__ me if I've posted the issue in a wrong place.

I'm currently translating the programming language Rust into Japanese. After fetching and merging the main repository's changes to my one, the issue starts to occur.
Backquoted strings in headers(lines beginning with `sharps`) and the index page(that is, in SUMMARY.md) would become links to themselves after running `mdbook`. Because it has no effect except that clicking them would jump you to exactly where you were, it appears to not matter. But I'd like to fix it because I think it looks ugly.

I'm a Japanese so I'm using `mdbook` in a Japanese environment. Maybe that would cause the problem?
But then how can I fix it? Or maybe for other reasons?

Could anyone help me addressing and resolving the problem?

**Comment by budziq** [comment]
Hi @hazama-yuinyan 

We'll gladly try to help :smile_cat: 

> so forgive me if I've posted the issue in a wrong place.

If there are problems with rendering then it is either problem with mdbook or with our markdown renderer [pulldown-cmark](https://github.com/google/pulldown-cmark) so asking for help here is a good start :+1: 

Here are some things that you may do to help us analyze the problem:
- Are you able to provide a simplified minimal reproducing sample of the problem (SUMMARY.md with single entry and a single Markdown file with just the problematic text/markup)
- describe what are your expectations in more detail (you can also upload screenshots with github comments).

**Comment by budziq** [comment]
![screenshot_2017-08-14_16-17-08](https://user-images.githubusercontent.com/221000/29275732-5d793294-810c-11e7-8dbe-38bb2b2d1bfe.png) (build from rust-book master with mdbook 0.0.22 from crates.io)

If you were describing the above screenshot. Then this seams to be the intended behaviour based on css used in current rust book. They have either not published a html version for some time so this would explain why the version from their master build with mdbook today looks different than one published in the web.

**Comment by hazama-yuinyan** [comment]
Thank you for the quick reply :)
> If you were describing the above screenshot.

Yes, that's exactly what I tried to explain.
> Then this seams to be the intended behavior based on css used in current rust book.

I see it's exactly what you are saying. Oh, this is my fault. Then thank you for taking your time to investigate and explain it to me.

I will close the issue.

**Comment by xftroxgpx** [comment]
Interesting,
this seems related: https://github.com/rust-lang/book/issues/1115
(at least the last line in the OP explains the same outcome as [here](https://github.com/rust-lang-nursery/mdBook/issues/405#issuecomment-322204687))

**Comment by hazama-yuinyan** [comment]
hmm, what's wrong with you?
I think that it's now resolved because the CSS caused the html to look like the above screenshot. Then what's your another matter? Why did you comment on a closed issue ;-)
