### ISSUE TITLE
mdbook seems to ignore subdirectories

### ISSUE THREAD

**Issue by frankmcsherry** [azerupi/mdBook#406]
When I put together a `SUMMARY.md` like so:

```
# Summary

[Timely Dataflow](./introduction.md)

- [Motivation](./chapter_0/chapter_0.md)
    - [A Meaningful Example](./chapter_0/chapter_0_1.md)
    - [When to use Timely Dataflow](./chapter_0/chapter_0_2.md)
    - [When not to use Timely Dataflow](./chapter_0/chapter_0_3.md)
```

with all of the files where expected, `mdbook` finds none of them and produces an empty book announcing only **Chapter 1**, with no pages or anything.

At the same time, the links seem totally legit, and you can click around in the `SUMMARY.md` file just fine: 

https://github.com/frankmcsherry/timely-dataflow/blob/master/mdbook/src/SUMMARY.md

This became a problem only when I created subdirectories for each of the chapters, so I imagine that is related somehow? If all of the content live in the `src/` directory it all seems great, but subdirectories of `src/` seem to cause problems.

**Comment by azerupi** [comment]
Thanks for the bug report!
This should normally work. The example book has files in sub-directories too, but that seems to work. 
I will take a look at this in the coming days and see if I can reproduce it on my machine.

**Comment by azerupi** [comment]
I tried with the master branch and the summary snippet you gave.
I let mdBook generate all the files corresponding to that structure and I get a perfectly working book. I am going to try with the repository you gave to see if I can reproduce it there.

**Comment by frankmcsherry** [comment]
Ok, I'm not sure. I've just gone and tried `mdbook build` again, and now it is all hunky-dory. I'm not sure what was causing the problem. =/ I'll try and catch it in the act again and see if I can isolate what was causing the problem (this wasn't the first time, but it does work at the moment).

**Comment by frankmcsherry** [comment]
I can't repro, but if it does it again I'll be back! :)

**Comment by azerupi** [comment]
Sure, no problem! Don't hesitate to post issues or feature requests. :)
