### ISSUE TITLE
breaking changes, intentional or not?

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#412]
I haven't been keeping up with mdbook super well, but [upgrading to 0.0.23 for rust-lang](https://github.com/steveklabnik/rust/tree/upgrade-mdbook) has a *ton* of breakage. After fixing up the internals, I'm getting things like:

* fragments like `#associated-functions` are now `#associated functions`
* the unstable book uses nested pages, and headers aren't generating the correct links, that is, `unstable-book\library-features\windows-stdio.html:89: broken link - unstable-book\windows-stdio.html` (note the missing `library-features` path.

Were these changes intentional, or did they slip through?

**Comment by azerupi** [comment]
No, both of those changes seem strange and unintentional to me.
Could you perhaps create two issues for them with some more info to reproduce?

**Comment by steveklabnik** [comment]
> Could you perhaps create two issues for them with some more info to reproduce?

Will do!
