### ISSUE TITLE
Breakage: fragments like `#associated-functions` are now `#associated functions`

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#416]
Originally filed as https://github.com/azerupi/mdBook/issues/412

Headings with spaces in the titles, like this:

```markdown
## Associated Functions
```

Used to generate an id of `#associated-functions`. They now generate `#associated functions`.

Sample book here: https://github.com/steveklabnik/mdbook-bug-report/tree/master/416

**Comment by behnam** [comment]
Looks like this diff changed the logic in an unexpected way: https://github.com/azerupi/mdBook/commit/33f3bec3019d49da62c88b094b10b3c7e592907c#diff-22028e040c17d23dbccf8fc78c428d53R465

I'm working on fix for this and <https://github.com/azerupi/mdBook/issues/417> to unblock the Cargo book.
