### ISSUE TITLE
Right left arrows overlap the text if the width is shunk too much

### ISSUE THREAD

**Issue by mdinger** [azerupi/mdBook#42]
The arrows overlap the text when the width is too small. See the picture.

![mdbook](https://cloud.githubusercontent.com/assets/4156987/9501011/aa12a312-4bf6-11e5-9f5d-0d5e3d43771c.png)

**Comment by azerupi** [comment]
Thanks for reporting! I will fix it next week when I am done with my exams :)

**Comment by azerupi** [comment]
It's fixed now, they appear on the bottom of the page on smaller screens and are more visible.

**Comment by mdinger** [comment]
Cool. Looks pretty nice.
