### ISSUE TITLE
Inline mathematics documentation is contradictory

### ISSUE THREAD

**Issue by dvberkel** [azerupi/mdBook#424]
The online documentation for [inline equations](azerupi.github.io/mdBook/format/mathjax.html) specify that

> Inline equations are delimited by `\\[` and `\\]`.

The example code shows

> `\\( \int x dx = \frac{x^2}{2} + C \\)`

Which has different delimiters

**Comment by clarcharr** [comment]
Both work; perhaps that could be documented instead?

**Comment by dvberkel** [comment]
:+1: 

I will update the pull-request and document both possibilities.

**Comment by dvberkel** [comment]
:+1:  I will revert back to the original pull request :-)
