### ISSUE TITLE
Paragraph links are broken for pages in sub-folders

### ISSUE THREAD

**Issue by dvberkel** [azerupi/mdBook#426]
As seen in the online documentation, e.g. that of [Mathjax Support](http://azerupi.github.io/mdBook/format/mathjax.html), clicking on a header of a page in a sub-folder creates the wrong URL.

For example, clicking the inline mathematics header results in the URL

```
http://azerupi.github.io/mdBook/mathjax.html#inline%20equations
```

which should be

```
http://azerupi.github.io/mdBook/format/mathjax.html#inline%20equations
```

**Comment by steveklabnik** [comment]
I believe this is a dup of https://github.com/azerupi/mdBook/issues/417 ?

**Comment by dvberkel** [comment]
Yes, this seems to be a duplicate. 

Sorry for the noise. I will close this issue.
