### ISSUE TITLE
Have a dark theme available which the user can enable

### ISSUE THREAD

**Issue by mdinger** [azerupi/mdBook#43]
Dark themes are much easier on the eyes especially when the user finds them agitating and too bright. I actually wouldn't move away from gitbook without dark theme support because of it.

This pic is rustbyexample in dark theme mode:

![rustbyexample](https://cloud.githubusercontent.com/assets/4156987/9501081/09e4ecd2-4bf7-11e5-80be-ed3abd822f98.png)

**Comment by azerupi** [comment]
Closed with #48
