### ISSUE TITLE
Chapter named "print.html" brings up print dialog

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#435]
A chapter like this:

    - [Formatted print](hello/print.md) 

when navigated to, brings up the print dialog.

I think we should check that it's the root's `print.html`, instead of any chapter named `print`.

**Comment by steveklabnik** [comment]
This is effectively blocking RBE using mdbook.

**Comment by azerupi** [comment]
https://github.com/azerupi/mdBook/blob/master/src/theme/book.js#L91

Is the line that is responsible for this behavior. I am not sure how we should change it yet.

**Comment by budziq** [comment]
I've been looking into it. Actually the print.md and print.html is hardcoded in few places in hbs_renderrer.rs to.

we can change it to something less likely to collide like:
- single_page_print.html
- cHJpbnQ_print.html with "cHJpbnQ" being base64 for "print" ;)
- {{some random string prefix}}_print.html (dynamically generated or hardcoded)

**Comment by steveklabnik** [comment]
I wonder if this shouldn't be generated specifically on the print page, rather than on all pages and checking if it's the right one.

**Comment by azerupi** [comment]
>I wonder if this shouldn't be generated specifically on the print page, rather than on all pages and checking if it's the right one.

Yes..! That is the best way to go!
Conditionally include an inline javascript snippet on the print page. It should be fairly easy to do with handlebars and will be the most robust solution. :+1:

**Comment by budziq** [comment]
Right! But there would be still collision of the single page page printed content with any page generated from `print.md` -> `print.html`

**Comment by azerupi** [comment]
Hmmm I think that is acceptable?
We reserve the `print.html` name as well as `index.html` name at the root. We could lint for it too.

**Comment by steveklabnik** [comment]
>  We reserve the print.html name as well as index.html name at the root. We could lint for it too.

This seems fine for me.

**Comment by budziq** [comment]
:+1:
