### ISSUE TITLE
Use the index finger icon on the menu toggle thing

### ISSUE THREAD

**Issue by mdinger** [azerupi/mdBook#44]
This menu item uses the "text insertion mouse pointer" and not the click on things "index finger pointer". This should be fixed. 

(the screengrab software seems to ignore the mouse)
![menu_pointer](https://cloud.githubusercontent.com/assets/4156987/9501449/657586d6-4bf9-11e5-82c1-545299290e87.png)

**Comment by azerupi** [comment]
I see what you mean, I will change it :)
