### ISSUE TITLE
Add tooltips for icons

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#442]
@shepmaster suggested tooltips for the various buttons, and I think it's a great idea! 
<img width="55" alt="buttons" src="https://user-images.githubusercontent.com/27786/30445643-a5e9f774-9954-11e7-9c85-57de0c83994a.png">
 isn't very obvious

**Comment by azerupi** [comment]
Closing as a duplicate of #388 :)

**Comment by steveklabnik** [comment]
Gah! sorry about that!
