### ISSUE TITLE
Theme confusion

### ISSUE THREAD

**Issue by jacwah** [azerupi/mdBook#464]
I noticed the styling of the online Rust book being very weird today. I didn't remember it looking that way the last time I visited it (some months ago). Just resetting the theme with the drop-down menu fixed the issue.

After some digging around I found the `theme` key in local storage and played around with it a bit. Setting it to a bogus value restored the weird styling I saw before.

<img width="1278" alt="screenshot" src="https://user-images.githubusercontent.com/3816754/31280119-94824e9c-aaab-11e7-9f9e-f1ef70d7a6ce.png">

My guess is that I had a theme set in local storage from before, but that it is no longer available in mdbook/the book. Unfortunately, I can no longer verify this as picking a theme overrode what was there before.

Maybe mdbook should detect an invalid theme and use the default style in that case. What do you think?

Relevant code:
https://github.com/azerupi/mdBook/blob/a6d4881e00527290d8d3843376b137842c5b2833/src/theme/book.js#L9-L13
https://github.com/azerupi/mdBook/blob/a6d4881e00527290d8d3843376b137842c5b2833/src/theme/book.js#L119-L151

**Comment by steveklabnik** [comment]
This should have been fixed by https://github.com/azerupi/mdBook/pull/449

can you try clearing out local storage and trying again?

**Comment by jacwah** [comment]
To be clear, everything is working fine after clearing local storage or setting a theme from the menu. I no longer have the problem because setting the theme clobbered the offending value.

It doesn't look like #449 is being served. https://doc.rust-lang.org/book/second-edition/store.js is a 404, so my browser is using a cached version which uses the `theme` (not `mdbook-theme`) key! Maybe that's the culprit here?

**Comment by steveklabnik** [comment]
You're looking at the stable URL there, you need to look at nightly to see store.js.
