### ISSUE TITLE
Some styling (theme) doesn't load in Chrome

### ISSUE THREAD

**Issue by anirudh24seven** [azerupi/mdBook#479]
I was trying to read Rust's documentation locally when I noticed that it doesn't contain some styling. I was asked to check my browser console and there was an issue with accessing local storage. This is because I am blocking third-party cookies in Chrome (default settings).

Issue doesn't happen in Firefox 56.0.2 (or when I disable "Block third-party cookies" in Chrome).

# Styling issue screenshots:
### Actual:
![screen shot 2017-10-29 at 11 06 06 pm](https://user-images.githubusercontent.com/617443/32206972-bd7b42a0-be1e-11e7-94f5-d26ee9d2b5f6.png)

### Expected:
![screen shot 2017-10-29 at 11 06 19 pm](https://user-images.githubusercontent.com/617443/32206981-c961b11c-be1e-11e7-955f-83cd2fc7a237.png)

## Console log error
![screen shot 2017-10-30 at 12 36 05 am](https://user-images.githubusercontent.com/617443/32206990-dc1210d6-be1e-11e7-906a-490d5f105ca6.png)

## Specific error line
![screen shot 2017-10-30 at 12 36 20 am](https://user-images.githubusercontent.com/617443/32207047-4c3fdbae-be1f-11e7-8ec6-00a1ad8b1873.png)

## Chrome version: 62.0.3202.75
![screen shot 2017-10-31 at 9 23 36 am](https://user-images.githubusercontent.com/617443/32206960-adbfdb3c-be1e-11e7-81a1-35ee01839cd6.png)

## Twitter thread detailing issue
https://twitter.com/anirudh24seven/status/924692085080338432

**Comment by budziq** [comment]
Hi, this is fixed in mdbook since 0.0.26 but the 
TRPL has not upgraded yet.

ping @steveklabnik

**Comment by steveklabnik** [comment]
Ah ha! I didn't know this. We've upgraded to 0.0.26 on master, I believe that it'll be in beta too, but most importantly, this will end up being fixed by a new release, maybe the next one, maybe the one after that. Thanks so much for reporting @anirudh24seven !
