### ISSUE TITLE
Math formula support ?

### ISSUE THREAD

**Issue by waynenilsen** [azerupi/mdBook#49]
Great work with this project! I would love to see mathjax or katex integration. I use math formulas frequently and pandoc supports this. Here is a render from pandoc with mathjax integration

![image](https://cloud.githubusercontent.com/assets/3612857/9798562/bfc9fd92-57cf-11e5-976e-ca0019b19505.png)

and the same thing in mdbook

![image](https://cloud.githubusercontent.com/assets/3612857/9798575/cf3bc530-57cf-11e5-81a8-4a13bba697ce.png)

I am using them in parallel for this reason right now.

**Comment by azerupi** [comment]
I would love that too ;) Actually that is one of the features I want most, because I plan to use mdBook for my school notes. But the best place to implement this is in the markdown parser ([pulldown-cmark](https://github.com/google/pulldown-cmark)). There is already a [request](https://github.com/google/pulldown-cmark/issues/6) there, but it's not very active.

**Comment by azerupi** [comment]
I added the MathJax JS files (from the CDN) you can already add math equations but sometimes it collides with the markdown rules, for example:
`*$$ 1 * 2 + 3 = 5 $$` works but `*$$1*2+3=5$$` does not.

**Comment by waynenilsen** [comment]
Yea, I agree that it should be in the markdown parser. As a workaround you could sanitize the MD by replacing the math with random, non-repeating characters a-z and keeping a lookup table, then putting the math back into the generated HTML. Maybe there is an easier way?

**Comment by azerupi** [comment]
At the moment, it should work using:

**Blocks**
```
\\[ Your math here... \\]
```
**Inline**
```
\\( Your math here... \\)
```

You have to dubble-escape, because the markdown parser is going to remove one backslash. I have used this and I haven't had any problems. The dollar signs do not work well and would need support in the markdown parser.
