### ISSUE TITLE
Use stylus (css-preprocessor) instead of vanilla css

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#57]
Stylus is a lot more powerful and clean to work with, the only downside is that it requires node.js to work. The dependency on node.js is only needed to generate the css from the stylus files.

At the moment I use a build script to generate the css on every build, but how does that affect users who use mdBook as library? Ideally they should not need node.js, the css should be generated before pushing a version on crates.io

Current work: bd99a4382f051817f6e0eebc2fff6cc43afbca02

**Comment by azerupi** [comment]
@mdinger I have reworked the whole stylehseet, migrated from vanilla css to stylus. You may be interested.

The gains from the switch are mainly an improvement in readability / maintainability, because stylus is modular, and adding / modifying themes is now easy as hell.

The downside is that it adds a dependency on node.js... And I don't want users to need node.js when compiling for their projects. I need to figure out how to trigger the css generation when I develop but prevent it when compiled as a library. At the moment it is triggered with a build script. On every build.

**Comment by mdinger** [comment]
That's pretty cool and looks so much simpler. I think my only comment is for the rust theme. Because the mobile next chapter buttons have a pretty dark background, you might have to check to be sure the highlightable icon is still visible if it retains the icon themes of the other buttons. I think that background contrast is different from the other themes. I'm not sure though as I didn't test out the branch to try it.

**Comment by azerupi** [comment]
You are right, the contrast on hover is not great. I may have to add an independent variable for the mobile-nav-icons, fortunately that is now very easy. ;) 

In the normal state it is looking good.

![image](https://cloud.githubusercontent.com/assets/7647338/9972128/d61763d0-5e61-11e5-9441-b1aea8e5a742.png)

**Comment by mdinger** [comment]
Cool. Yeah, it looks like it should be easy. Nice.
