### ISSUE TITLE
Prepare for publishing v0.0.2 to crates.io

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#59]
I think it's time to publish a new version to crates.io, there have been a lot of improvements since v0.0.1.

- [x] Check if the docs are still up to date
- [x] Regenerate css before publishing
- [x] Publish to crates.io

@mdinger if you find any last minute bugs to fix before publishing to crates.io, let me know ;)

**Comment by mdinger** [comment]
Nothing obvious beside this:

1. Go to [formatting](http://azerupi.github.io/mdBook/format/format.html) and leave sidebar enabled
2. Go to the next page
3. Close the sidebar
4. Click back on the browser
5. The sidebar returns until you refresh

I'm not sure how to fix this...

**Comment by azerupi** [comment]
I can not reproduce this issue on Chrome, are you using Firefox?

**Comment by mdinger** [comment]
Yeah. I don't have chrome installed. Back just doesn't trigger refresh I guess so it returns to the way the previous page was (which shouldn't be accurate anymore regardless...).

**Comment by azerupi** [comment]
ok, I am not sure I can do anything about that on my side though

**Comment by mdinger** [comment]
You're right. Chrome doesn't do that. It works fine with gitbook so it looks like there is some way to deal with it. Changing the theme does the same thing. Odd

**Comment by mdinger** [comment]
They say firefox triggers onload() on back. Are themes and sidebars adjusted at onload? I haven't checked yet.

**Comment by azerupi** [comment]
It seems to be a cache problem. When hitting back, Firefox reloads the page from cache like it was before leaving. This means that all the javascript has been executed and will not run a second time. 

I found a good explanation in this [StackOverflow answer](http://stackoverflow.com/a/2639165/3980369)

**Comment by azerupi** [comment]
Could you try again in a couple of minutes, when the new commit has been deployed?

**Comment by mdinger** [comment]
You can also seem to fix it via manually calling the [pageshow event](https://developer.mozilla.org/en-US/docs/Web/Events/pageshow)

**Comment by mdinger** [comment]
Yeah, it works perfectly now. There probably should be a dedicated before pageload script. Then, instead of rerunning everything, you can just reset all localstorage settings on pageshow.

**Comment by azerupi** [comment]
I am glad it works, I will leave it like this for now. But feel free to make a new issue so that I remember to experiment and improve this for the next versions :)

**Comment by mdinger** [comment]
Sure
