### ISSUE TITLE
Create a before load script

### ISSUE THREAD

**Issue by mdinger** [azerupi/mdBook#60]
Making sure the theme is preserved on load and when clicking back and such requires rerunning [all scripts](https://github.com/azerupi/mdBook/issues/59#issuecomment-143042764). It might be good to consolidate all before page load scripts together for better structure but also so the local storage items can be triggered alone without everything having to run.

For example, the current script [doesn't even check](https://github.com/azerupi/mdBook/blob/master/src/theme/index.hbs#L35-L37) if the correct highlighting css files are enabled. Though this used to be an issue, rerunning all scripts on page load probably brute force solved the issue. It still doesn't seem like a neat solution.

**Comment by azerupi** [comment]
This will probably change with #90
