### ISSUE TITLE
Improve speed of renderer?

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#63]
I am not sure if it is needed and if it is easy to do but the renderer is a little bit slow to start. 
Speed improvements are always good.

**Comment by steveklabnik** [comment]
Is this about the speed of `mdbook build` or something like https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Frust-lang.github.io%2Fbook%2F ?

**Comment by azerupi** [comment]
When I made this issue I was under the impression that the rendering (`mdbook build`) was slower than with previous versions. I don't have any evidence to support that though. 

I filed this issue to look into it at some point, maybe there is some low hanging fruit that could improve the speed. 

You are testing it on a large book, how do you feel about the performance?

**Comment by steveklabnik** [comment]
Zero issues, it's plenty fast. 0.16 seconds to render the whole book.

**Comment by azerupi** [comment]
I guess I was wrong then, I can close this issue. Thanks! :)
