### ISSUE TITLE
New release to crates.io?

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#67]
Right now, 'cargo install' won't install mdbook, because 0.0.2 doesn't compile.

**Comment by azerupi** [comment]
It doesn't? I will take a look right away, thanks for informing me!

**Comment by azerupi** [comment]
It is caused by the update from handlebars 0.11.x to 0.12.x, the version on crates.io did not yet have specified versions for dependencies. The current version in master works fine thanks to the PR from @kbknapp. I will upload that now!

**Comment by steveklabnik** [comment]
Thanks so much :)

**Comment by azerupi** [comment]
It works now! :)
