### ISSUE TITLE
`mdbook test`

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#69]
This would be a subcommand that runs `rustdoc --test` on each of the source files and reports what happened.

**Comment by azerupi** [comment]
That would be a good addition, though I am more inclined to use `mdbook test rust` or something equivalent, to avoid being constrained if I eventually want to add other tests in the future.

For the implementation, does rustdoc have a Rust API or should I use `std::process::Command`?

**Comment by steveklabnik** [comment]
> to avoid being constrained if I eventually want to add other tests in the future.

well, I would assume a top-level `test` would run all tests of all kinds... so that might not be a problem. Depends on what you want to do :smile: 

> For the implementation, does rustdoc have a Rust API or should I use std::process::Command?

It does have a Rust API, but it's hard to use given that it's not on crates.io. I would at least start with `Command`, given that [that's what rustbook does](https://github.com/rust-lang/rust/blob/master/src/rustbook/test.rs#L45-L48) currently.

If we end up being able to put librustdoc up on crates.io in the future, doing it that way might be more robust, but at least you can know that everyone who has Rust installed with have `rustdoc`, at least.

**Comment by azerupi** [comment]
>well, I would assume a top-level test would run all tests of all kinds... so that might not be a problem. Depends on what you want to do

You are right ;)

When using `Command` do you know of a way to check if `rustdoc` is present on the system before running the command?

**Comment by steveklabnik** [comment]
You'd use regular shell things, I guess.


Btw I mentioned this to @achrichto this evening and he confirmed Command is the way to go.
