### ISSUE TITLE
rendering graves in TOC

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#70]
Using graves for code styling as the title of a chapter works:

![2015-12-14-114347_107x91_scrot](https://cloud.githubusercontent.com/assets/27786/11787090/fd4e6482-a257-11e5-93c3-b65cdbd1360b.png)

but renders literally in the sidebar:

![2015-12-14-114343_123x34_scrot](https://cloud.githubusercontent.com/assets/27786/11787075/eeec2ab4-a257-11e5-8560-423e971ded12.png)

I _think_ the right thing to do here would be to just strip them on the sidebar, but I could see giving them some code styling too.

**Comment by azerupi** [comment]
Yes, markdown in the sidebar is not rendered at the moment. I am not sure if it should or not. I will do some tests and see what works best. 

I read that you are trying out this crate for the official rust book and I am really flattered! :) I have to warn though, I have exams until end of January so I will not have a lot of time to work on it. If you need some changes sooner, you can send PR's. I will try to respond as quickly as I can. Or I can add you as contributor if you find it more convenient.

**Comment by steveklabnik** [comment]
Yes. :)

Cool. I had wanted to ping you, I don't want to make it a burden, but also didn't want to implement PRs if you wanted to tackle them! Nothing here is super high priority, so I might send a fix, I might wait. But I certainly don't expect anyone to have a ton of free time until after the new year. :+1:

**Comment by azerupi** [comment]
>didn't want to implement PRs if you wanted to tackle them!

I don't mind, I am always glad to see PR's! Just let me know if you are working on something, so that we avoid duplicate work :wink:
