### ISSUE TITLE
Automatically create anchors for section headers

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#72]
If I write something like this:

```
## Foo
```

and I want to link to it later, I have to do this:

```
<a href="#foo">
## Foo
</a>
```

or the equivalent. GitHub and rustbook generate these kinds of links automatically, which keeps source files cleaner. Example: https://github.com/rust-lang/rust/#quick-start

**Comment by azerupi** [comment]
If I implement this in mdbook it's going to be an ugly hack, I would have to either parse the markdown a second time myself or parse the html outputted by pulldown-cmark.

I think this should be implemented in the markdown parser. But pulldown-cmark hasn't seen any activity in a while, so I doubt that is going to happen anytime soon. :/

**Comment by steveklabnik** [comment]
Ah interesting, I should check up on `pulldown-cmark`.

**Comment by asolove** [comment]
Since `pulldown-cmark` is striving to match the CommonMark spec, I think it's unlikely they would accept a PR for this non-standard behavior. It would be pretty trivial to do this in JS after the fact, though, as long as you had a clear rule for how to turn a run of text into an anchor name that can't have spaces.

**Comment by azerupi** [comment]
>It would be pretty trivial to do this in JS after the fact

Yeah, but I had in mind that the browser wasn't going to scroll down if anchors were added after page load. Obviously I was wrong :wink:  Thanks for the PR!

>Since pulldown-cmark is striving to match the CommonMark spec, I think it's unlikely they would accept a PR for this non-standard behavior.

It's pretty common to add anchors to headings in web-dev, I don't understand why this isn't part of the spec yet..

And one neat thing about Rust, is that you can easily gate some parts of your code behind `Features`, non-standard additions could be feature-gated and off by default. :)
