### ISSUE TITLE
Hiding parts of examples

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#73]
Rustdoc has a feature that allows you to hide parts of examples:

```
fn another_function(x: i32) {
# }
```

This will hide the closing }, but allow the example to compile. This is really useful for hiding parts of examples which confuse the point, yet allow them to still compile.

![2015-12-17-125058_223x62_scrot](https://cloud.githubusercontent.com/assets/27786/11877352/c2eb5072-a4bc-11e5-8dcc-f99a6d9b13fa.png)

**Comment by azerupi** [comment]
I could add this but I am a little worried it might conflict with some code snippets. For example, if you want to show some python example and have line comments in it, the comments will not be shown. 

An easy way to solve this might be to enable this only for rust code.

**Comment by steveklabnik** [comment]
> An easy way to solve this might be to enable this only for rust code.

Yeah, that seems like a reasonable compromise, if this is a feature you're willing to support.

**Comment by azerupi** [comment]
**Thought to myself:**
Maybe this could be implemented as a javascript plugin?

**Comment by steveklabnik** [comment]
Oh that's interesting...

**Comment by steveklabnik** [comment]
Actually, that idea is really great. I don't have time to type it all out right now, but this would solve a big problem we have with this feature...

**Comment by azerupi** [comment]
>Actually, that idea is really great. I don't have time to type it all out right now, but this would solve a big problem we have with this feature...

Would that be the show/hide full examples problem? Or something else entirely? :)

**Comment by steveklabnik** [comment]
Yeah, the fact that people don't always see the context. It causes lots of issues in the stdlib with try!, specifically...

**Comment by azerupi** [comment]
Yes, I have seen the debates :wink: 

I will try to hack something nice together, unless someone else beats me to it.

**Comment by azerupi** [comment]
This should now work. For the moment only in Rust code, but this could be generalized in the future with a little work. I have also added an expand / collapse button, to show / hide the lines. 

I haven't done a lot of testing so there could be some rough edges.
