### ISSUE TITLE
Dark theme messes up inline code blocks

### ISSUE THREAD

**Issue by steveklabnik** [azerupi/mdBook#74]
Source:

```
    This `let` statement has this form:
```

light (and Rust):

![2015-12-21-130315_264x38_scrot](https://cloud.githubusercontent.com/assets/27786/11937584/23de4a0a-a7e3-11e5-9593-c07f12e57257.png)

navy (and coal):

![2015-12-21-130411_205x77_scrot](https://cloud.githubusercontent.com/assets/27786/11937601/45dc7820-a7e3-11e5-9e20-ae5ff2af3f8c.png)

**Comment by azerupi** [comment]
Does that occur for all inline code blocks?

**Comment by steveklabnik** [comment]
The random ones I checked seemed to, yeah.
