### ISSUE TITLE
Styling tables?

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#91]
I have added basic formatting (center, padding, bold headers, ...) to the tables so that they look OK but I haven't added borders or colors.

@steveklabnik do you have any requests about the style of the tables? It's not urgent, you can take your time to test it and give feedback later :)

**Comment by steveklabnik** [comment]
Screenshot for posterity 
![2016-01-04-091757_318x198_scrot](https://cloud.githubusercontent.com/assets/27786/12091300/00a5ed18-b2c4-11e5-9763-2d56d68657a4.png)

They look pretty fine to me. A small line might be nice.

> I haven't added borders or colors.

@charlotteis mentioned in another issue that gray backgrounds tend to be bad for accessibility, so the only thing I'd say is that any additional changes should ideally take that into account.

**Comment by Charlotteis** [comment]
It really depends, but here is a tool to work out if it looks good! http://leaverou.github.io/contrast-ratio/
Compare the colour of your background and the colour of your text. The higher (and greener) the number, the better contrast ratio you have and the more visible/accessible your text will be :D

**Comment by azerupi** [comment]
Nice, thanks for the link!

I will experiment with borders, eventually post some screenshots here for feedback. I thought about adding a background color to only header elements, but I am not sure yet.

**Comment by Charlotteis** [comment]
Looking forward to see it, thanks for the great work :)

**Comment by azerupi** [comment]
I have styled the tables in a local branch, here is what it looks like for the different themes:
![table-light](https://cloud.githubusercontent.com/assets/7647338/12852722/be4db190-cc30-11e5-833b-c7c60c689527.png)
![table-coal](https://cloud.githubusercontent.com/assets/7647338/12852721/be250fa6-cc30-11e5-8293-01b797680f8a.png)
![table-navy](https://cloud.githubusercontent.com/assets/7647338/12852723/be4ebbda-cc30-11e5-807a-f24702d3f217.png)
![table-rust](https://cloud.githubusercontent.com/assets/7647338/12852724/be54e62c-cc30-11e5-858f-abe7a33a003f.png)

Feedback? I am not very fond of the colors with the rust theme.

**Comment by azerupi** [comment]
I pushed this, I think it looks pretty good

**Comment by steveklabnik** [comment]
I like it :+1:

**Comment by Charlotteis** [comment]
Would it be possible to check the contrast values? I don't think the grey on black is going to be very accessible. Try putting the colours through http://leaverou.github.io/contrast-ratio/. If the contrast ratio is green, then we're good to go :)

**Comment by azerupi** [comment]
You mean the contrast values between the header-row background color and the text color right?

| Theme  | Contrast value | Color |
| ------------- | ------------- | -------------|
| Light  | 7.9  | Green |
| Rust  | 6.3 | Green |
| Navy  | 5.4 | Green |
| Coal  | 3.7 | Orange |

The colors used in the coal theme are not green... But I don't feel like it's a big deal in this case for the following reasons:

- It's only one row, the header row. The text is bold and in theory it should contain only a couple keywords
- It's a dark / night theme, if there is trouble reading it you can switch to the other themes

What do you think?

**Comment by steveklabnik** [comment]
I think it would take very minor tweaks to get from 3.7 to something that passes.

**Comment by azerupi** [comment]
Probably, but it has to look good too ;) 
I will try to fiddle around, see if something works

**Comment by azerupi** [comment]
I get a contrast value of 5.0 now :)

**Comment by steveklabnik** [comment]
:+1:

**Comment by Charlotteis** [comment]
thank you, sorry for being so pedantic but we're making the world more accessible together \o/

**Comment by azerupi** [comment]
No worries, it's for a good cause :) Thanks
