### ISSUE TITLE
Block quotes are not styled correctly in the Crates.io version

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#92]
I don't know what happened here, the right style is present in the git version that has not been updated since the push to Crates.io

**Comment by asolove** [comment]
Can you give more detail of what it's supposed to look like? I see blockquotes styled in a reasonableish way.

**Comment by azerupi** [comment]
>I see blockquotes styled in a reasonableish way.

Indeed it seems to be resolved now. :+1: 

Maybe it was caused by the fact that I released two version to Crates.io in a very short time (couple of minutes) because of an  annoying bug. Maybe Cargo hadn't updated it's database yet or was still using a cached version. I don't know, but it works now apparently. Thanks for pointing that out :)
