### ISSUE TITLE
watch command could serve the results

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#93]
In the future I could imagine that the watch command serves the generated result to `localhost` updating in real time without needing a refresh. The served version could eventually be modified directly from the browser.

This needs a little thought but it would be a nice way to play a little with Rust's webdev ecosystem.

**Comment by jessestricker** [comment]
Very nice idea!
If this is going to be implemented, a browser live-refresh is a must-have!

I will be happy to use `mdbook watch --serve`. :+1:
